language: python
sudo: false

python:
    - 3.3
    - 3.4
    - 3.5

env:
    - PYTHONASYNCIODEBUG=x
    - PYTHONASYNCIODEBUG=

install:
    - pip install flake8
    - pip install -U pytest
    - pip install pytest-cov
    - pip install .
    - pip install codecov

script:
  - make cov

after_success:
  - codecov
