language: python
sudo: false

python:
    - 3.4
    - 3.5
    - 3.6

matrix:
  include:
    - python: '3.6'
      env: TOKIO="y"
  allow_failures:
    - env: TOKIO="y"

install:
    - pip install flake8
    - pip install -U pytest
    - pip install pytest-cov
    - pip install .
    - pip install codecov
    - |
        export RUST_VERSION=1.17.0
        python -c "import sysconfig; print('\n'.join(map(repr,sorted(sysconfig.get_config_vars().items()))))"
        mkdir ~/rust-installer
        curl -sL https://static.rust-lang.org/rustup.sh -o ~/rust-installer/rustup.sh
        sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=$RUST_VERSION -y --disable-sudo
        export PATH="$HOME/rust/bin:$PATH"
        export PYTHON_LIB=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
        find $PYTHON_LIB
        export LIBRARY_PATH="$LIBRARY_PATH:$PYTHON_LIB"
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PYTHON_LIB:$HOME/rust/lib"
        rustc -V
        if [ "$TOKIO" = "y" ]; then
          pip install -U git+git://github.com/PyO3/tokio.git@master
        fi;

script:
  - make cov

after_success:
  - codecov


deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: "Pl5Ra/KR0OqE27w8leDsIMzS/K65IEQCtwvuNTrXr6KHZT4hgAwtMS+Up22Ow8J5858nLHzJ0OQKIWPJ8dirZkc8E3fNkFFImK4y4aGkzuDVhQG5Y+Mmj+7UglIEu1/3i/MPmfCftUTuLsUyleYaq/MdGF6zvDoM+H0+DSYgxMA="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.5
