language: python

python:
    - 3.3
    - 3.4
    - 3.5
env:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=0

install:
    - pip install flake8
    - pip install nose
    - pip install .
    - pip install coveralls

script:
  - make cov

after_success:
  - coveralls
